// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package provider

import (
	"context"
	"encoding/json"

	"github.com/Khan/genqlient/graphql"
)

// Team includes the GraphQL fields of Teams requested by the fragment Team.
type Team struct {
	Name                        string   `json:"name"`
	BoolEmptyDefault            bool     `json:"boolEmptyDefault"`
	BoolKnownDefault            bool     `json:"boolKnownDefault"`
	NullableBool                *bool    `json:"nullableBool"`
	NullableBoolEmptyDefault    *bool    `json:"nullableBoolEmptyDefault"`
	NullableBoolKnownDefault    *bool    `json:"nullableBoolKnownDefault"`
	StringEmptyDefault          string   `json:"stringEmptyDefault"`
	StringKnownDefault          string   `json:"stringKnownDefault"`
	StringRandomDefault         string   `json:"stringRandomDefault"`
	NullableString              *string  `json:"nullableString"`
	NullableStringEmptyDefault  *string  `json:"nullableStringEmptyDefault"`
	NullableStringKnownDefault  *string  `json:"nullableStringKnownDefault"`
	NullableStringRandomDefault *string  `json:"nullableStringRandomDefault"`
	FloatEmptyDefault           float64  `json:"floatEmptyDefault"`
	FloatKnownDefault           float64  `json:"floatKnownDefault"`
	FloatRandomDefault          float64  `json:"floatRandomDefault"`
	NullableFloat               *float64 `json:"nullableFloat"`
	NullableFloatEmptyDefault   *float64 `json:"nullableFloatEmptyDefault"`
	NullableFloatKnownDefault   *float64 `json:"nullableFloatKnownDefault"`
	NullableFloatRandomDefault  *float64 `json:"nullableFloatRandomDefault"`
	NestedBoolEmptyDefault      bool    `json:"nestedBoolEmptyDefault"`
}

// GetName returns Team.Name, and is useful for accessing the field via an interface.
func (v *Team) GetName() string { return v.Name }

// GetBoolEmptyDefault returns Team.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetBoolEmptyDefault() bool { return v.BoolEmptyDefault }

// GetBoolKnownDefault returns Team.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetBoolKnownDefault() bool { return v.BoolKnownDefault }

// GetNullableBool returns Team.NullableBool, and is useful for accessing the field via an interface.
func (v *Team) GetNullableBool() *bool { return v.NullableBool }

// GetNullableBoolEmptyDefault returns Team.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableBoolEmptyDefault() *bool { return v.NullableBoolEmptyDefault }

// GetNullableBoolKnownDefault returns Team.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableBoolKnownDefault() *bool { return v.NullableBoolKnownDefault }

// GetStringEmptyDefault returns Team.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetStringEmptyDefault() string { return v.StringEmptyDefault }

// GetStringKnownDefault returns Team.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetStringKnownDefault() string { return v.StringKnownDefault }

// GetStringRandomDefault returns Team.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *Team) GetStringRandomDefault() string { return v.StringRandomDefault }

// GetNullableString returns Team.NullableString, and is useful for accessing the field via an interface.
func (v *Team) GetNullableString() *string { return v.NullableString }

// GetNullableStringEmptyDefault returns Team.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableStringEmptyDefault() *string { return v.NullableStringEmptyDefault }

// GetNullableStringKnownDefault returns Team.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableStringKnownDefault() *string { return v.NullableStringKnownDefault }

// GetNullableStringRandomDefault returns Team.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableStringRandomDefault() *string { return v.NullableStringRandomDefault }

// GetFloatEmptyDefault returns Team.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetFloatEmptyDefault() float64 { return v.FloatEmptyDefault }

// GetFloatKnownDefault returns Team.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetFloatKnownDefault() float64 { return v.FloatKnownDefault }

// GetFloatRandomDefault returns Team.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *Team) GetFloatRandomDefault() float64 { return v.FloatRandomDefault }

// GetNullableFloat returns Team.NullableFloat, and is useful for accessing the field via an interface.
func (v *Team) GetNullableFloat() *float64 { return v.NullableFloat }

// GetNullableFloatEmptyDefault returns Team.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableFloatEmptyDefault() *float64 { return v.NullableFloatEmptyDefault }

// GetNullableFloatKnownDefault returns Team.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableFloatKnownDefault() *float64 { return v.NullableFloatKnownDefault }

// GetNullableFloatRandomDefault returns Team.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNullableFloatRandomDefault() *float64 { return v.NullableFloatRandomDefault }

// GetNestedBoolEmptyDefault returns Team.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *Team) GetNestedBoolEmptyDefault() bool { return v.NestedBoolEmptyDefault }

type TeamsInsertInput struct {
	NullableString              *string `json:"nullableString"`
	BoolEmptyDefault            bool    `json:"boolEmptyDefault"`
	BoolKnownDefault            bool    `json:"boolKnownDefault"`
	StringKnownDefault          string  `json:"stringKnownDefault"`
	NullableBool                *bool   `json:"nullableBool"`
	NullableBoolEmptyDefault    *bool   `json:"nullableBoolEmptyDefault"`
	NullableBoolKnownDefault    *bool   `json:"nullableBoolKnownDefault"`
	NullableStringKnownDefault  *string `json:"nullableStringKnownDefault"`
	NullableStringRandomDefault *string `json:"nullableStringRandomDefault,omitempty"`
	Name                        string  `json:"name,omitempty"`
	StringRandomDefault         *string `json:"stringRandomDefault,omitempty"`
	StringEmptyDefault          string  `json:"stringEmptyDefault"`
	NullableStringEmptyDefault  *string `json:"nullableStringEmptyDefault"`
	FloatEmptyDefault           float64  `json:"floatEmptyDefault"`
	FloatKnownDefault           float64  `json:"floatKnownDefault"`
	NullableFloat               *float64 `json:"nullableFloat"`
	NullableFloatEmptyDefault   *float64 `json:"nullableFloatEmptyDefault"`
	NullableFloatKnownDefault   *float64 `json:"nullableFloatKnownDefault"`
	FloatRandomDefault          *float64 `json:"floatRandomDefault,omitempty"`
	NullableFloatRandomDefault  *float64 `json:"nullableFloatRandomDefault,omitempty"`
	NestedBoolEmptyDefault      bool    `json:"nestedBoolEmptyDefault"`
}

// GetNullableString returns TeamsInsertInput.NullableString, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableString() *string { return v.NullableString }

// GetBoolEmptyDefault returns TeamsInsertInput.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetBoolEmptyDefault() bool { return v.BoolEmptyDefault }

// GetBoolKnownDefault returns TeamsInsertInput.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetBoolKnownDefault() bool { return v.BoolKnownDefault }

// GetStringKnownDefault returns TeamsInsertInput.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetStringKnownDefault() string { return v.StringKnownDefault }

// GetNullableBool returns TeamsInsertInput.NullableBool, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableBool() *bool { return v.NullableBool }

// GetNullableBoolEmptyDefault returns TeamsInsertInput.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableBoolEmptyDefault() *bool { return v.NullableBoolEmptyDefault }

// GetNullableBoolKnownDefault returns TeamsInsertInput.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableBoolKnownDefault() *bool { return v.NullableBoolKnownDefault }

// GetNullableStringKnownDefault returns TeamsInsertInput.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableStringKnownDefault() *string {
	return v.NullableStringKnownDefault
}

// GetNullableStringRandomDefault returns TeamsInsertInput.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableStringRandomDefault() *string {
	return v.NullableStringRandomDefault
}

// GetName returns TeamsInsertInput.Name, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetName() string { return v.Name }

// GetStringRandomDefault returns TeamsInsertInput.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetStringRandomDefault() *string { return v.StringRandomDefault }

// GetStringEmptyDefault returns TeamsInsertInput.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetStringEmptyDefault() string { return v.StringEmptyDefault }

// GetNullableStringEmptyDefault returns TeamsInsertInput.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableStringEmptyDefault() *string {
	return v.NullableStringEmptyDefault
}

// GetFloatEmptyDefault returns TeamsInsertInput.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetFloatEmptyDefault() float64 { return v.FloatEmptyDefault }

// GetFloatKnownDefault returns TeamsInsertInput.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetFloatKnownDefault() float64 { return v.FloatKnownDefault }

// GetNullableFloat returns TeamsInsertInput.NullableFloat, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableFloat() *float64 { return v.NullableFloat }

// GetNullableFloatEmptyDefault returns TeamsInsertInput.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableFloatEmptyDefault() *float64 {
	return v.NullableFloatEmptyDefault
}

// GetNullableFloatKnownDefault returns TeamsInsertInput.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableFloatKnownDefault() *float64 {
	return v.NullableFloatKnownDefault
}

// GetFloatRandomDefault returns TeamsInsertInput.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetFloatRandomDefault() *float64 { return v.FloatRandomDefault }

// GetNullableFloatRandomDefault returns TeamsInsertInput.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNullableFloatRandomDefault() *float64 {
	return v.NullableFloatRandomDefault
}

// GetNestedBoolEmptyDefault returns TeamsInsertInput.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsInsertInput) GetNestedBoolEmptyDefault() bool { return v.NestedBoolEmptyDefault }

type TeamsUpdateInput struct {
	NullableString              *string `json:"nullableString"`
	BoolEmptyDefault            bool    `json:"boolEmptyDefault"`
	BoolKnownDefault            bool    `json:"boolKnownDefault"`
	StringKnownDefault          string  `json:"stringKnownDefault"`
	NullableBool                *bool   `json:"nullableBool"`
	NullableBoolEmptyDefault    *bool   `json:"nullableBoolEmptyDefault"`
	NullableBoolKnownDefault    *bool   `json:"nullableBoolKnownDefault"`
	NullableStringKnownDefault  *string `json:"nullableStringKnownDefault"`
	NullableStringRandomDefault *string `json:"nullableStringRandomDefault,omitempty"`
	Name                        string  `json:"name,omitempty"`
	StringRandomDefault         *string `json:"stringRandomDefault,omitempty"`
	StringEmptyDefault          string  `json:"stringEmptyDefault"`
	NullableStringEmptyDefault  *string `json:"nullableStringEmptyDefault"`
	FloatEmptyDefault           float64  `json:"floatEmptyDefault"`
	FloatKnownDefault           float64  `json:"floatKnownDefault"`
	NullableFloat               *float64 `json:"nullableFloat"`
	NullableFloatEmptyDefault   *float64 `json:"nullableFloatEmptyDefault"`
	NullableFloatKnownDefault   *float64 `json:"nullableFloatKnownDefault"`
	FloatRandomDefault          *float64 `json:"floatRandomDefault,omitempty"`
	NullableFloatRandomDefault  *float64 `json:"nullableFloatRandomDefault,omitempty"`
	NestedBoolEmptyDefault      bool    `json:"nestedBoolEmptyDefault"`
}

// GetNullableString returns TeamsUpdateInput.NullableString, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableString() *string { return v.NullableString }

// GetBoolEmptyDefault returns TeamsUpdateInput.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetBoolEmptyDefault() bool { return v.BoolEmptyDefault }

// GetBoolKnownDefault returns TeamsUpdateInput.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetBoolKnownDefault() bool { return v.BoolKnownDefault }

// GetStringKnownDefault returns TeamsUpdateInput.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetStringKnownDefault() string { return v.StringKnownDefault }

// GetNullableBool returns TeamsUpdateInput.NullableBool, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableBool() *bool { return v.NullableBool }

// GetNullableBoolEmptyDefault returns TeamsUpdateInput.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableBoolEmptyDefault() *bool { return v.NullableBoolEmptyDefault }

// GetNullableBoolKnownDefault returns TeamsUpdateInput.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableBoolKnownDefault() *bool { return v.NullableBoolKnownDefault }

// GetNullableStringKnownDefault returns TeamsUpdateInput.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableStringKnownDefault() *string {
	return v.NullableStringKnownDefault
}

// GetNullableStringRandomDefault returns TeamsUpdateInput.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableStringRandomDefault() *string {
	return v.NullableStringRandomDefault
}

// GetName returns TeamsUpdateInput.Name, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetName() string { return v.Name }

// GetStringRandomDefault returns TeamsUpdateInput.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetStringRandomDefault() *string { return v.StringRandomDefault }

// GetStringEmptyDefault returns TeamsUpdateInput.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetStringEmptyDefault() string { return v.StringEmptyDefault }

// GetNullableStringEmptyDefault returns TeamsUpdateInput.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableStringEmptyDefault() *string {
	return v.NullableStringEmptyDefault
}

// GetFloatEmptyDefault returns TeamsUpdateInput.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetFloatEmptyDefault() float64 { return v.FloatEmptyDefault }

// GetFloatKnownDefault returns TeamsUpdateInput.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetFloatKnownDefault() float64 { return v.FloatKnownDefault }

// GetNullableFloat returns TeamsUpdateInput.NullableFloat, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableFloat() *float64 { return v.NullableFloat }

// GetNullableFloatEmptyDefault returns TeamsUpdateInput.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableFloatEmptyDefault() *float64 {
	return v.NullableFloatEmptyDefault
}

// GetNullableFloatKnownDefault returns TeamsUpdateInput.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableFloatKnownDefault() *float64 {
	return v.NullableFloatKnownDefault
}

// GetFloatRandomDefault returns TeamsUpdateInput.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetFloatRandomDefault() *float64 { return v.FloatRandomDefault }

// GetNullableFloatRandomDefault returns TeamsUpdateInput.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNullableFloatRandomDefault() *float64 {
	return v.NullableFloatRandomDefault
}

// GetNestedBoolEmptyDefault returns TeamsUpdateInput.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *TeamsUpdateInput) GetNestedBoolEmptyDefault() bool { return v.NestedBoolEmptyDefault }

// __createTeamInput is used internally by genqlient
type __createTeamInput struct {
	Input TeamsInsertInput `json:"input"`
}

// GetInput returns __createTeamInput.Input, and is useful for accessing the field via an interface.
func (v *__createTeamInput) GetInput() TeamsInsertInput { return v.Input }

// __deleteTeamInput is used internally by genqlient
type __deleteTeamInput struct {
	Name string `json:"name"`
}

// GetName returns __deleteTeamInput.Name, and is useful for accessing the field via an interface.
func (v *__deleteTeamInput) GetName() string { return v.Name }

// __getTeamInput is used internally by genqlient
type __getTeamInput struct {
	Name string `json:"name"`
}

// GetName returns __getTeamInput.Name, and is useful for accessing the field via an interface.
func (v *__getTeamInput) GetName() string { return v.Name }

// __updateTeamInput is used internally by genqlient
type __updateTeamInput struct {
	Input TeamsUpdateInput `json:"input"`
	Name  string           `json:"name"`
}

// GetInput returns __updateTeamInput.Input, and is useful for accessing the field via an interface.
func (v *__updateTeamInput) GetInput() TeamsUpdateInput { return v.Input }

// GetName returns __updateTeamInput.Name, and is useful for accessing the field via an interface.
func (v *__updateTeamInput) GetName() string { return v.Name }

// createTeamInsertIntoTeamsCollectionTeamsInsertResponse includes the requested fields of the GraphQL type TeamsInsertResponse.
type createTeamInsertIntoTeamsCollectionTeamsInsertResponse struct {
	// Array of records impacted by the mutation
	Records []createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams `json:"records"`
}

// GetRecords returns createTeamInsertIntoTeamsCollectionTeamsInsertResponse.Records, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponse) GetRecords() []createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams {
	return v.Records
}

// createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams includes the requested fields of the GraphQL type Teams.
type createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams struct {
	Team `json:"-"`
}

// GetName returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.Name, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetName() string {
	return v.Team.Name
}

// GetBoolEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetBoolEmptyDefault() bool {
	return v.Team.BoolEmptyDefault
}

// GetBoolKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetBoolKnownDefault() bool {
	return v.Team.BoolKnownDefault
}

// GetNullableBool returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableBool, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableBool() *bool {
	return v.Team.NullableBool
}

// GetNullableBoolEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableBoolEmptyDefault() *bool {
	return v.Team.NullableBoolEmptyDefault
}

// GetNullableBoolKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableBoolKnownDefault() *bool {
	return v.Team.NullableBoolKnownDefault
}

// GetStringEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetStringEmptyDefault() string {
	return v.Team.StringEmptyDefault
}

// GetStringKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetStringKnownDefault() string {
	return v.Team.StringKnownDefault
}

// GetStringRandomDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetStringRandomDefault() string {
	return v.Team.StringRandomDefault
}

// GetNullableString returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableString, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableString() *string {
	return v.Team.NullableString
}

// GetNullableStringEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableStringEmptyDefault() *string {
	return v.Team.NullableStringEmptyDefault
}

// GetNullableStringKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableStringKnownDefault() *string {
	return v.Team.NullableStringKnownDefault
}

// GetNullableStringRandomDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableStringRandomDefault() *string {
	return v.Team.NullableStringRandomDefault
}

// GetFloatEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetFloatEmptyDefault() float64 {
	return v.Team.FloatEmptyDefault
}

// GetFloatKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetFloatKnownDefault() float64 {
	return v.Team.FloatKnownDefault
}

// GetFloatRandomDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetFloatRandomDefault() float64 {
	return v.Team.FloatRandomDefault
}

// GetNullableFloat returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableFloat, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableFloat() *float64 {
	return v.Team.NullableFloat
}

// GetNullableFloatEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableFloatEmptyDefault() *float64 {
	return v.Team.NullableFloatEmptyDefault
}

// GetNullableFloatKnownDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableFloatKnownDefault() *float64 {
	return v.Team.NullableFloatKnownDefault
}

// GetNullableFloatRandomDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNullableFloatRandomDefault() *float64 {
	return v.Team.NullableFloatRandomDefault
}

// GetNestedBoolEmptyDefault returns createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) GetNestedBoolEmptyDefault() bool {
	return v.Team.NestedBoolEmptyDefault
}

func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams
		graphql.NoUnmarshalJSON
	}
	firstPass.createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Team)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalcreateTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams struct {
	Name string `json:"name"`

	BoolEmptyDefault bool `json:"boolEmptyDefault"`

	BoolKnownDefault bool `json:"boolKnownDefault"`

	NullableBool *bool `json:"nullableBool"`

	NullableBoolEmptyDefault *bool `json:"nullableBoolEmptyDefault"`

	NullableBoolKnownDefault *bool `json:"nullableBoolKnownDefault"`

	StringEmptyDefault string `json:"stringEmptyDefault"`

	StringKnownDefault string `json:"stringKnownDefault"`

	StringRandomDefault string `json:"stringRandomDefault"`

	NullableString *string `json:"nullableString"`

	NullableStringEmptyDefault *string `json:"nullableStringEmptyDefault"`

	NullableStringKnownDefault *string `json:"nullableStringKnownDefault"`

	NullableStringRandomDefault *string `json:"nullableStringRandomDefault"`

	FloatEmptyDefault float64 `json:"floatEmptyDefault"`

	FloatKnownDefault float64 `json:"floatKnownDefault"`

	FloatRandomDefault float64 `json:"floatRandomDefault"`

	NullableFloat *float64 `json:"nullableFloat"`

	NullableFloatEmptyDefault *float64 `json:"nullableFloatEmptyDefault"`

	NullableFloatKnownDefault *float64 `json:"nullableFloatKnownDefault"`

	NullableFloatRandomDefault *float64 `json:"nullableFloatRandomDefault"`

	NestedBoolEmptyDefault bool `json:"nestedBoolEmptyDefault"`
}

func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *createTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams) __premarshalJSON() (*__premarshalcreateTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams, error) {
	var retval __premarshalcreateTeamInsertIntoTeamsCollectionTeamsInsertResponseRecordsTeams

	retval.Name = v.Team.Name
	retval.BoolEmptyDefault = v.Team.BoolEmptyDefault
	retval.BoolKnownDefault = v.Team.BoolKnownDefault
	retval.NullableBool = v.Team.NullableBool
	retval.NullableBoolEmptyDefault = v.Team.NullableBoolEmptyDefault
	retval.NullableBoolKnownDefault = v.Team.NullableBoolKnownDefault
	retval.StringEmptyDefault = v.Team.StringEmptyDefault
	retval.StringKnownDefault = v.Team.StringKnownDefault
	retval.StringRandomDefault = v.Team.StringRandomDefault
	retval.NullableString = v.Team.NullableString
	retval.NullableStringEmptyDefault = v.Team.NullableStringEmptyDefault
	retval.NullableStringKnownDefault = v.Team.NullableStringKnownDefault
	retval.NullableStringRandomDefault = v.Team.NullableStringRandomDefault
	retval.FloatEmptyDefault = v.Team.FloatEmptyDefault
	retval.FloatKnownDefault = v.Team.FloatKnownDefault
	retval.FloatRandomDefault = v.Team.FloatRandomDefault
	retval.NullableFloat = v.Team.NullableFloat
	retval.NullableFloatEmptyDefault = v.Team.NullableFloatEmptyDefault
	retval.NullableFloatKnownDefault = v.Team.NullableFloatKnownDefault
	retval.NullableFloatRandomDefault = v.Team.NullableFloatRandomDefault
	retval.NestedBoolEmptyDefault = v.Team.NestedBoolEmptyDefault
	return &retval, nil
}

// createTeamResponse is returned by createTeam on success.
type createTeamResponse struct {
	// Adds one or more `TeamsInsertResponse` records to the collection
	InsertIntoTeamsCollection createTeamInsertIntoTeamsCollectionTeamsInsertResponse `json:"insertIntoTeamsCollection"`
}

// GetInsertIntoTeamsCollection returns createTeamResponse.InsertIntoTeamsCollection, and is useful for accessing the field via an interface.
func (v *createTeamResponse) GetInsertIntoTeamsCollection() createTeamInsertIntoTeamsCollectionTeamsInsertResponse {
	return v.InsertIntoTeamsCollection
}

// deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse includes the requested fields of the GraphQL type TeamsDeleteResponse.
type deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse struct {
	// Count of the records impacted by the mutation
	AffectedCount int `json:"affectedCount"`
}

// GetAffectedCount returns deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse.AffectedCount, and is useful for accessing the field via an interface.
func (v *deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse) GetAffectedCount() int {
	return v.AffectedCount
}

// deleteTeamResponse is returned by deleteTeam on success.
type deleteTeamResponse struct {
	// Deletes zero or more records from the collection
	DeleteFromTeamsCollection deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse `json:"deleteFromTeamsCollection"`
}

// GetDeleteFromTeamsCollection returns deleteTeamResponse.DeleteFromTeamsCollection, and is useful for accessing the field via an interface.
func (v *deleteTeamResponse) GetDeleteFromTeamsCollection() deleteTeamDeleteFromTeamsCollectionTeamsDeleteResponse {
	return v.DeleteFromTeamsCollection
}

// getTeamResponse is returned by getTeam on success.
type getTeamResponse struct {
	// A pagable collection of type `Teams`
	TeamsCollection getTeamTeamsCollectionTeamsConnection `json:"teamsCollection"`
}

// GetTeamsCollection returns getTeamResponse.TeamsCollection, and is useful for accessing the field via an interface.
func (v *getTeamResponse) GetTeamsCollection() getTeamTeamsCollectionTeamsConnection {
	return v.TeamsCollection
}

// getTeamTeamsCollectionTeamsConnection includes the requested fields of the GraphQL type TeamsConnection.
type getTeamTeamsCollectionTeamsConnection struct {
	Edges []getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge `json:"edges"`
}

// GetEdges returns getTeamTeamsCollectionTeamsConnection.Edges, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnection) GetEdges() []getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge {
	return v.Edges
}

// getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge includes the requested fields of the GraphQL type TeamsEdge.
type getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge struct {
	Node getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams `json:"node"`
}

// GetNode returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge.Node, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdge) GetNode() getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams {
	return v.Node
}

// getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams includes the requested fields of the GraphQL type Teams.
type getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams struct {
	Team `json:"-"`
}

// GetName returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.Name, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetName() string {
	return v.Team.Name
}

// GetBoolEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetBoolEmptyDefault() bool {
	return v.Team.BoolEmptyDefault
}

// GetBoolKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetBoolKnownDefault() bool {
	return v.Team.BoolKnownDefault
}

// GetNullableBool returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableBool, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableBool() *bool {
	return v.Team.NullableBool
}

// GetNullableBoolEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableBoolEmptyDefault() *bool {
	return v.Team.NullableBoolEmptyDefault
}

// GetNullableBoolKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableBoolKnownDefault() *bool {
	return v.Team.NullableBoolKnownDefault
}

// GetStringEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetStringEmptyDefault() string {
	return v.Team.StringEmptyDefault
}

// GetStringKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetStringKnownDefault() string {
	return v.Team.StringKnownDefault
}

// GetStringRandomDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetStringRandomDefault() string {
	return v.Team.StringRandomDefault
}

// GetNullableString returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableString, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableString() *string {
	return v.Team.NullableString
}

// GetNullableStringEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableStringEmptyDefault() *string {
	return v.Team.NullableStringEmptyDefault
}

// GetNullableStringKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableStringKnownDefault() *string {
	return v.Team.NullableStringKnownDefault
}

// GetNullableStringRandomDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableStringRandomDefault() *string {
	return v.Team.NullableStringRandomDefault
}

// GetFloatEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetFloatEmptyDefault() float64 {
	return v.Team.FloatEmptyDefault
}

// GetFloatKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetFloatKnownDefault() float64 {
	return v.Team.FloatKnownDefault
}

// GetFloatRandomDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetFloatRandomDefault() float64 {
	return v.Team.FloatRandomDefault
}

// GetNullableFloat returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableFloat, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableFloat() *float64 {
	return v.Team.NullableFloat
}

// GetNullableFloatEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableFloatEmptyDefault() *float64 {
	return v.Team.NullableFloatEmptyDefault
}

// GetNullableFloatKnownDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableFloatKnownDefault() *float64 {
	return v.Team.NullableFloatKnownDefault
}

// GetNullableFloatRandomDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNullableFloatRandomDefault() *float64 {
	return v.Team.NullableFloatRandomDefault
}

// GetNestedBoolEmptyDefault returns getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) GetNestedBoolEmptyDefault() bool {
	return v.Team.NestedBoolEmptyDefault
}

func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams
		graphql.NoUnmarshalJSON
	}
	firstPass.getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Team)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalgetTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams struct {
	Name string `json:"name"`

	BoolEmptyDefault bool `json:"boolEmptyDefault"`

	BoolKnownDefault bool `json:"boolKnownDefault"`

	NullableBool *bool `json:"nullableBool"`

	NullableBoolEmptyDefault *bool `json:"nullableBoolEmptyDefault"`

	NullableBoolKnownDefault *bool `json:"nullableBoolKnownDefault"`

	StringEmptyDefault string `json:"stringEmptyDefault"`

	StringKnownDefault string `json:"stringKnownDefault"`

	StringRandomDefault string `json:"stringRandomDefault"`

	NullableString *string `json:"nullableString"`

	NullableStringEmptyDefault *string `json:"nullableStringEmptyDefault"`

	NullableStringKnownDefault *string `json:"nullableStringKnownDefault"`

	NullableStringRandomDefault *string `json:"nullableStringRandomDefault"`

	FloatEmptyDefault float64 `json:"floatEmptyDefault"`

	FloatKnownDefault float64 `json:"floatKnownDefault"`

	FloatRandomDefault float64 `json:"floatRandomDefault"`

	NullableFloat *float64 `json:"nullableFloat"`

	NullableFloatEmptyDefault *float64 `json:"nullableFloatEmptyDefault"`

	NullableFloatKnownDefault *float64 `json:"nullableFloatKnownDefault"`

	NullableFloatRandomDefault *float64 `json:"nullableFloatRandomDefault"`

	NestedBoolEmptyDefault bool `json:"nestedBoolEmptyDefault"`
}

func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *getTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams) __premarshalJSON() (*__premarshalgetTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams, error) {
	var retval __premarshalgetTeamTeamsCollectionTeamsConnectionEdgesTeamsEdgeNodeTeams

	retval.Name = v.Team.Name
	retval.BoolEmptyDefault = v.Team.BoolEmptyDefault
	retval.BoolKnownDefault = v.Team.BoolKnownDefault
	retval.NullableBool = v.Team.NullableBool
	retval.NullableBoolEmptyDefault = v.Team.NullableBoolEmptyDefault
	retval.NullableBoolKnownDefault = v.Team.NullableBoolKnownDefault
	retval.StringEmptyDefault = v.Team.StringEmptyDefault
	retval.StringKnownDefault = v.Team.StringKnownDefault
	retval.StringRandomDefault = v.Team.StringRandomDefault
	retval.NullableString = v.Team.NullableString
	retval.NullableStringEmptyDefault = v.Team.NullableStringEmptyDefault
	retval.NullableStringKnownDefault = v.Team.NullableStringKnownDefault
	retval.NullableStringRandomDefault = v.Team.NullableStringRandomDefault
	retval.FloatEmptyDefault = v.Team.FloatEmptyDefault
	retval.FloatKnownDefault = v.Team.FloatKnownDefault
	retval.FloatRandomDefault = v.Team.FloatRandomDefault
	retval.NullableFloat = v.Team.NullableFloat
	retval.NullableFloatEmptyDefault = v.Team.NullableFloatEmptyDefault
	retval.NullableFloatKnownDefault = v.Team.NullableFloatKnownDefault
	retval.NullableFloatRandomDefault = v.Team.NullableFloatRandomDefault
	retval.NestedBoolEmptyDefault = v.Team.NestedBoolEmptyDefault
	return &retval, nil
}

// updateTeamResponse is returned by updateTeam on success.
type updateTeamResponse struct {
	// Updates zero or more records in the collection
	UpdateTeamsCollection updateTeamUpdateTeamsCollectionTeamsUpdateResponse `json:"updateTeamsCollection"`
}

// GetUpdateTeamsCollection returns updateTeamResponse.UpdateTeamsCollection, and is useful for accessing the field via an interface.
func (v *updateTeamResponse) GetUpdateTeamsCollection() updateTeamUpdateTeamsCollectionTeamsUpdateResponse {
	return v.UpdateTeamsCollection
}

// updateTeamUpdateTeamsCollectionTeamsUpdateResponse includes the requested fields of the GraphQL type TeamsUpdateResponse.
type updateTeamUpdateTeamsCollectionTeamsUpdateResponse struct {
	// Array of records impacted by the mutation
	Records []updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams `json:"records"`
}

// GetRecords returns updateTeamUpdateTeamsCollectionTeamsUpdateResponse.Records, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponse) GetRecords() []updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams {
	return v.Records
}

// updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams includes the requested fields of the GraphQL type Teams.
type updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams struct {
	Team `json:"-"`
}

// GetName returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.Name, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetName() string {
	return v.Team.Name
}

// GetBoolEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.BoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetBoolEmptyDefault() bool {
	return v.Team.BoolEmptyDefault
}

// GetBoolKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.BoolKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetBoolKnownDefault() bool {
	return v.Team.BoolKnownDefault
}

// GetNullableBool returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableBool, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableBool() *bool {
	return v.Team.NullableBool
}

// GetNullableBoolEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableBoolEmptyDefault() *bool {
	return v.Team.NullableBoolEmptyDefault
}

// GetNullableBoolKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableBoolKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableBoolKnownDefault() *bool {
	return v.Team.NullableBoolKnownDefault
}

// GetStringEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.StringEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetStringEmptyDefault() string {
	return v.Team.StringEmptyDefault
}

// GetStringKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.StringKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetStringKnownDefault() string {
	return v.Team.StringKnownDefault
}

// GetStringRandomDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.StringRandomDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetStringRandomDefault() string {
	return v.Team.StringRandomDefault
}

// GetNullableString returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableString, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableString() *string {
	return v.Team.NullableString
}

// GetNullableStringEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableStringEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableStringEmptyDefault() *string {
	return v.Team.NullableStringEmptyDefault
}

// GetNullableStringKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableStringKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableStringKnownDefault() *string {
	return v.Team.NullableStringKnownDefault
}

// GetNullableStringRandomDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableStringRandomDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableStringRandomDefault() *string {
	return v.Team.NullableStringRandomDefault
}

// GetFloatEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.FloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetFloatEmptyDefault() float64 {
	return v.Team.FloatEmptyDefault
}

// GetFloatKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.FloatKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetFloatKnownDefault() float64 {
	return v.Team.FloatKnownDefault
}

// GetFloatRandomDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.FloatRandomDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetFloatRandomDefault() float64 {
	return v.Team.FloatRandomDefault
}

// GetNullableFloat returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableFloat, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableFloat() *float64 {
	return v.Team.NullableFloat
}

// GetNullableFloatEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableFloatEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableFloatEmptyDefault() *float64 {
	return v.Team.NullableFloatEmptyDefault
}

// GetNullableFloatKnownDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableFloatKnownDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableFloatKnownDefault() *float64 {
	return v.Team.NullableFloatKnownDefault
}

// GetNullableFloatRandomDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NullableFloatRandomDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNullableFloatRandomDefault() *float64 {
	return v.Team.NullableFloatRandomDefault
}

// GetNestedBoolEmptyDefault returns updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams.NestedBoolEmptyDefault, and is useful for accessing the field via an interface.
func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) GetNestedBoolEmptyDefault() bool {
	return v.Team.NestedBoolEmptyDefault
}

func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) UnmarshalJSON(b []byte) error {

	if string(b) == "null" {
		return nil
	}

	var firstPass struct {
		*updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams
		graphql.NoUnmarshalJSON
	}
	firstPass.updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams = v

	err := json.Unmarshal(b, &firstPass)
	if err != nil {
		return err
	}

	err = json.Unmarshal(
		b, &v.Team)
	if err != nil {
		return err
	}
	return nil
}

type __premarshalupdateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams struct {
	Name string `json:"name"`

	BoolEmptyDefault bool `json:"boolEmptyDefault"`

	BoolKnownDefault bool `json:"boolKnownDefault"`

	NullableBool *bool `json:"nullableBool"`

	NullableBoolEmptyDefault *bool `json:"nullableBoolEmptyDefault"`

	NullableBoolKnownDefault *bool `json:"nullableBoolKnownDefault"`

	StringEmptyDefault string `json:"stringEmptyDefault"`

	StringKnownDefault string `json:"stringKnownDefault"`

	StringRandomDefault string `json:"stringRandomDefault"`

	NullableString *string `json:"nullableString"`

	NullableStringEmptyDefault *string `json:"nullableStringEmptyDefault"`

	NullableStringKnownDefault *string `json:"nullableStringKnownDefault"`

	NullableStringRandomDefault *string `json:"nullableStringRandomDefault"`

	FloatEmptyDefault float64 `json:"floatEmptyDefault"`

	FloatKnownDefault float64 `json:"floatKnownDefault"`

	FloatRandomDefault float64 `json:"floatRandomDefault"`

	NullableFloat *float64 `json:"nullableFloat"`

	NullableFloatEmptyDefault *float64 `json:"nullableFloatEmptyDefault"`

	NullableFloatKnownDefault *float64 `json:"nullableFloatKnownDefault"`

	NullableFloatRandomDefault *float64 `json:"nullableFloatRandomDefault"`

	NestedBoolEmptyDefault bool `json:"nestedBoolEmptyDefault"`
}

func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) MarshalJSON() ([]byte, error) {
	premarshaled, err := v.__premarshalJSON()
	if err != nil {
		return nil, err
	}
	return json.Marshal(premarshaled)
}

func (v *updateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams) __premarshalJSON() (*__premarshalupdateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams, error) {
	var retval __premarshalupdateTeamUpdateTeamsCollectionTeamsUpdateResponseRecordsTeams

	retval.Name = v.Team.Name
	retval.BoolEmptyDefault = v.Team.BoolEmptyDefault
	retval.BoolKnownDefault = v.Team.BoolKnownDefault
	retval.NullableBool = v.Team.NullableBool
	retval.NullableBoolEmptyDefault = v.Team.NullableBoolEmptyDefault
	retval.NullableBoolKnownDefault = v.Team.NullableBoolKnownDefault
	retval.StringEmptyDefault = v.Team.StringEmptyDefault
	retval.StringKnownDefault = v.Team.StringKnownDefault
	retval.StringRandomDefault = v.Team.StringRandomDefault
	retval.NullableString = v.Team.NullableString
	retval.NullableStringEmptyDefault = v.Team.NullableStringEmptyDefault
	retval.NullableStringKnownDefault = v.Team.NullableStringKnownDefault
	retval.NullableStringRandomDefault = v.Team.NullableStringRandomDefault
	retval.FloatEmptyDefault = v.Team.FloatEmptyDefault
	retval.FloatKnownDefault = v.Team.FloatKnownDefault
	retval.FloatRandomDefault = v.Team.FloatRandomDefault
	retval.NullableFloat = v.Team.NullableFloat
	retval.NullableFloatEmptyDefault = v.Team.NullableFloatEmptyDefault
	retval.NullableFloatKnownDefault = v.Team.NullableFloatKnownDefault
	retval.NullableFloatRandomDefault = v.Team.NullableFloatRandomDefault
	retval.NestedBoolEmptyDefault = v.Team.NestedBoolEmptyDefault
	return &retval, nil
}

func createTeam(
	ctx context.Context,
	client graphql.Client,
	input TeamsInsertInput,
) (*createTeamResponse, error) {
	req := &graphql.Request{
		OpName: "createTeam",
		Query: `
mutation createTeam ($input: TeamsInsertInput!) {
	insertIntoTeamsCollection(objects: [$input]) {
		records {
			... Team
		}
	}
}
fragment Team on Teams {
	name
	boolEmptyDefault
	boolKnownDefault
	nullableBool
	nullableBoolEmptyDefault
	nullableBoolKnownDefault
	stringEmptyDefault
	stringKnownDefault
	stringRandomDefault
	nullableString
	nullableStringEmptyDefault
	nullableStringKnownDefault
	nullableStringRandomDefault
	floatEmptyDefault
	floatKnownDefault
	floatRandomDefault
	nullableFloat
	nullableFloatEmptyDefault
	nullableFloatKnownDefault
	nullableFloatRandomDefault
	nestedBoolEmptyDefault
}
`,
		Variables: &__createTeamInput{
			Input: input,
		},
	}
	var err error

	var data createTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func deleteTeam(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*deleteTeamResponse, error) {
	req := &graphql.Request{
		OpName: "deleteTeam",
		Query: `
mutation deleteTeam ($name: String!) {
	deleteFromTeamsCollection(filter: {name:{eq:$name}}) {
		affectedCount
	}
}
`,
		Variables: &__deleteTeamInput{
			Name: name,
		},
	}
	var err error

	var data deleteTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func getTeam(
	ctx context.Context,
	client graphql.Client,
	name string,
) (*getTeamResponse, error) {
	req := &graphql.Request{
		OpName: "getTeam",
		Query: `
query getTeam ($name: String!) {
	teamsCollection(filter: {name:{eq:$name}}) {
		edges {
			node {
				... Team
			}
		}
	}
}
fragment Team on Teams {
	name
	boolEmptyDefault
	boolKnownDefault
	nullableBool
	nullableBoolEmptyDefault
	nullableBoolKnownDefault
	stringEmptyDefault
	stringKnownDefault
	stringRandomDefault
	nullableString
	nullableStringEmptyDefault
	nullableStringKnownDefault
	nullableStringRandomDefault
	floatEmptyDefault
	floatKnownDefault
	floatRandomDefault
	nullableFloat
	nullableFloatEmptyDefault
	nullableFloatKnownDefault
	nullableFloatRandomDefault
	nestedBoolEmptyDefault
}
`,
		Variables: &__getTeamInput{
			Name: name,
		},
	}
	var err error

	var data getTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func updateTeam(
	ctx context.Context,
	client graphql.Client,
	input TeamsUpdateInput,
	name string,
) (*updateTeamResponse, error) {
	req := &graphql.Request{
		OpName: "updateTeam",
		Query: `
mutation updateTeam ($input: TeamsUpdateInput!, $name: String!) {
	updateTeamsCollection(set: $input, filter: {name:{eq:$name}}) {
		records {
			... Team
		}
	}
}
fragment Team on Teams {
	name
	boolEmptyDefault
	boolKnownDefault
	nullableBool
	nullableBoolEmptyDefault
	nullableBoolKnownDefault
	stringEmptyDefault
	stringKnownDefault
	stringRandomDefault
	nullableString
	nullableStringEmptyDefault
	nullableStringKnownDefault
	nullableStringRandomDefault
	floatEmptyDefault
	floatKnownDefault
	floatRandomDefault
	nullableFloat
	nullableFloatEmptyDefault
	nullableFloatKnownDefault
	nullableFloatRandomDefault
	nestedBoolEmptyDefault
}
`,
		Variables: &__updateTeamInput{
			Input: input,
			Name:  name,
		},
	}
	var err error

	var data updateTeamResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
